// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	DATABASE_URL: string;
	DIRECT_URL: string;
	JWT_SECRET: string;
	GOOGLE_GENERATIVE_AI_API_KEY: string;
}
